{
 "title": "MM2 Dash",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Avg Data Transfer / Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_mirror_source_connector_byte_rate{topic=\"source.app-cliente-v1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Records Transfer / Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kafka_connect_mirror_source_connector_record_rate{topic=\"source.app-cliente-v1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(kafka_connect_mirror_source_connector_replication_latency_ms{topic=\"source.app-cliente-v1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Records LAG",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag{topic=\"app-cliente-v1\"}) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}